export const CART_TOPIC = {
  GET_ALL_ITEMS: "GET_ALL_ITEMS",
  ADD_ITEM_CART: "ADD_ITEM_CART",
  DELETE_ITEM_CART: "DELETE_ITEM_CART",
};

export const PRODUCT_TOPIC = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
};

export const APP_TOPIC = {
  CHANGE_MODE: "CHANGE_MODE",
};

export const COUNTER_TOPIC = {
  INC_COUNTER: "INC_COUNTER",
};
